### ISSUE TITLE
Handling permission denied or no camera/mic error

### ISSUE THREAD

**Issue by medicalwei** [voc/kevin#1]
This is the first thing I've encountered, and since that's a missing feature compared to obs.ninja, I think it's good to note here.

**Comment by derchrisuk** [comment]
How is that visible?
When you "not allow" device on the browser popup ?

**Comment by medicalwei** [comment]
Christian Gerbrandt <notifications@github.com>於 2020年12月23日 週三，19:09寫道：

> How is that visible?
> When you "not allow" device on the browser popup ?
>

I set my iOS Safari to deny location, camera and mic requests by default...

> --
Yao Wei

**Comment by derchrisuk** [comment]
I don't know what is supposed to happen here.
When you deny access to cam/mic then obviously nothing is working.

**Comment by medicalwei** [comment]
There's no message telling that one has to enable any of the permissions to
use Kevin.

In my case Kevin just shown up in blank screen and there was no message
that permission is denied from the browser.  And since I set the browser to deny these by default so there's no dialog for the permissions.

![254C0124-E535-468B-A8C3-467303C3F813](https://user-images.githubusercontent.com/74481/103044962-91ab7300-45bd-11eb-9c7a-e9a63ce6648a.png)

**Comment by lukas2511** [comment]
Just ran into the same issue. Didn't have a camera connected so no permission dialog popped up, only an empty page visible.

**Comment by derchrisuk** [comment]
I just added an check which throws an error when no devices are detected.
