### ISSUE TITLE
[Feature][Required] Minimal CSS for Video view links to maximize video element on Page

### ISSUE THREAD

**Issue by ebosseck** [voc/kevin#10]
Add minimal CSS to the Video view to maximize the video source on the visible part of the browser page, so the video fills either the entire height or the entire width, without changing aspect ratio or cutting parts of the video element off.

**Comment by derchrisuk** [comment]
It already does fill the whole view.
There are 3x different output resolutions, 360p, 720p and 1080p.
Depending on which one you will use, you have to use the same dimensions for the browser source in OBS
