### ISSUE TITLE
Ask before closing a tab

### ISSUE THREAD

**Issue by muellermartin** [voc/kevin#16]
Show a dialoge before closing a tab with an active webcam or screen sharing source to prevent accidental loss of streams during production.

**Comment by derchrisuk** [comment]
I don't think this is possible

**Comment by muellermartin** [comment]
It should be possible with a [onbeforeunload](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload) event handler.

**Comment by derchrisuk** [comment]
Nope, just tested it

**Comment by derchrisuk** [comment]
I tried all 3 variants now:

- body onbeforeunload
- window.addEventListener
- window.onbeforeunload

None was showing me a message

**Comment by muellermartin** [comment]
Hm, I see. I also tested it and it just prevents reloading the page. Maybe this is also unwanted, but this is not the same…

**Comment by derchrisuk** [comment]
Message on Close does work in Chrome, not Firefox
Message on Reload works in both

**Comment by derchrisuk** [comment]
I added my testing to the current running version.
It will now only send a message when a share is active.
And i tested it on both FF and Chrome, which was working fine.
