### ISSUE TITLE
It is impossble to share a v4l2 loopback device as a camera

### ISSUE THREAD

**Issue by fhars** [voc/kevin#17]
If you click on "share webcam", the video preview obscures the "Close" and "Start" buttons of the "Preview" dialog, making it impossible to continue (with a v4l2 loopback device, in both in chromium and firefox on Ubuntu 20.10).

**Comment by derchrisuk** [comment]
Is this still happening?
I only pushed the feature a few minutes ago.

**Comment by fhars** [comment]
No, that works now
