### ISSUE TITLE
Bitte Namen überdenken

### ISSUE THREAD

**Issue by medialepfade** [voc/kevin#19]
ausführliche Diskussion hier: https://twitter.com/c3voc/status/1341548901330014209

**Comment by derpeter** [comment]
Bitte leg doch dein Anliegen hier dar und verlinke nicht die schon total schief gelaufene Twitter Diskussion. Wenn dir wirklich daran liegt etwas zu erreichen dann ist das doch vollkommen falsche weg. :-(

**Comment by Reshief** [comment]
Also ich finde es tatsächlich ziemlich cool, dass mal ein System Kevin benannt wurde. 
Finde den Zusammenhang zu Kevinismus aus dem Twitter-Thread sehr an den Haaren herbeigezogen. 

Außerdem, wenn Kevin nicht mal in einem anderen Kontext als in geschmacklosen Witzen und dummen Sprüchen verwendet wird, bekommt man die Konnotation natürlich auch nicht weg. 
Habe es persönlich sehr begrüßt, davon zu hören 👍 :)
