### ISSUE TITLE
Capability of switching between cameras and mic sources (front/back/etc)

### ISSUE THREAD

**Issue by medicalwei** [voc/kevin#2]
This is especially useful for phones that their back camera is far better than the front one.

**Comment by adlerweb** [comment]
This also affects Chromium users. Here KEVIN uses the first camera available and Chromium doesn't really offer a native way to switch to other sources. A device chooser like other tools implement would be a good idea.

**Comment by derchrisuk** [comment]
Switch as in while the session is already running?

**Comment by adlerweb** [comment]
As far as I can tell there is no direct possibility to switch cameras - running or not. I only get asked if I want to allow camera/microphone but not which device to use. Afterwards the browser shows a drop down list for devices but it is grayed out.
![kevin](https://user-images.githubusercontent.com/1146482/103025146-7acf3700-4551-11eb-9dd1-ee86f74bccf8.png)

**Comment by derchrisuk** [comment]
Should work now with implementation of #9
