### ISSUE TITLE
Streaming two sources (webcam + desktop) simultaneously does not work

### ISSUE THREAD

**Issue by muellermartin** [voc/kevin#3]
Currently it is not possible to use KEVIN to stream two sources (e.g. webcam and desktop capture) simultaneously in one browser.

When a second tab/window is used to stream another source, the error message "Someone already created this room. Please either join or create a separate room." is shown. Using two different browsers (or one window in private mode) works though.

As using multiple browsers is not always possible or not good from a usability point of view, it would be nice if KEVIN could provide multiple simultaneos streams (e.g. in different tabs).

**Comment by derchrisuk** [comment]
A new random id is now generated on each access.
