### ISSUE TITLE
[Feature][Required] Minimal Configuration Dialog for Senders (with selections possibly encoded in url parameters)

### ISSUE THREAD

**Issue by ebosseck** [voc/kevin#9]
Create a minimal configuration dialog to show senders before they are sending video feeds. 
This should Include initially:

- Webcam/Screenshare Selection
- Audio Source Selection
- a big button to start Streaming

At a Later stage this could also contain:
- Basic quality settings (Video only, for audio we should always go for the best. Mostly this setting should make it possible for speakers to select lower video resolution/bitrate presets if they know they are on a low-bandwidth network)
- Advanced settings for full quality control (Video Resolution / Codec / Bitrate, Audio Settings, ....), this should be expandable and collapsed by default, as not to confuse people not knowing what they should select there.

Webcam / Screenshare Selection is importand, because as mentioned in #2, not all browsers (esp. chromium based browsers) have a native way of selecting video devices.

**Comment by derchrisuk** [comment]
First draft for Webcam preview has been commited.
At the moment it will only show you the video device preview.
Looking into adding selection buttons for source selection, as well as audio preview.

**Comment by derchrisuk** [comment]
Just added Webcam preview.
You can select your Audio/Video source from a dropdown, and they will be selected when you click on Start.

**Comment by derchrisuk** [comment]
And a vumeter for Audio
